version: '3'

services:
  web:
    stdin_open: true
    tty: true
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pa$$word
      POSTGRES_DB: movie_review_dev
      ELASTIC_HOST: "elasticsearch"
    volumes:
      - .:/usr/src/app

  database:
      image: postgres
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: pa$$word
        POSTGRES_DB: movie_review_dev
      volumes:
  
       - db-data:/data/db

volumes:
  db-data: